name: GitHub Actions Demo
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  init:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 20.x ]
    steps:
    - uses: actions/checkout@v4
    - name: Starting on Node.js ${{matrix.node-version}}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install modules
      run: |
          cd client
          npm install
    - name: Eslint fix
      run: |
        cd client
        npx eslint . --fix
    - name: Build project
      run: |
          cd client
          npm run build
    - name: Start project
      run: |
          cd client
          npm run start
    - name: Linting
      run: |
          cd client
          npm run lint
